// web/src/views/DetailView.tsx
import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { SectionEyebrow } from '@/components/primitives';
import { useContent } from '@/hooks/useContent';
import { t } from '@/i18n';
import { localized } from '@/lib/utils';
import type { Experience, Locale, Project } from '@/types';

export function DetailView({
  locale,
  kind,
  slug,
  navigate,
}: {
  locale: Locale;
  kind: 'project' | 'experience';
  slug: string;
  navigate: (to: string) => void;
}) {
  const store = useContent();
  const copy = t(locale);
  const [item, setItem] = useState<Project | Experience>();
  const [loading, setLoading] = useState(true);
  const isProject = kind === 'project';
  const { project, experience, data: homeData } = store;

  useEffect(() => {
    let cancelled = false;
    async function load() {
      setLoading(true);
      const next = isProject ? await project(slug) : await experience(slug);
      if (!cancelled) {
        setItem(next);
        setLoading(false);
        if (next) {
          const title =
            'title' in next ? localized(next.title, locale) : localized(next.org, locale);
          document.title = `${title} · gutsyang`;
        }
      }
    }
    void load();
    return () => {
      cancelled = true;
    };
  }, [experience, isProject, locale, project, slug]);

  const items = useMemo(
    () => (isProject ? homeData?.projects ?? [] : homeData?.experiences ?? []),
    [homeData, isProject],
  );
  const index = items.findIndex((entry) => entry.slug === slug);
  const previous = index > 0 ? items[index - 1] : undefined;
  const next = index >= 0 ? items[index + 1] : undefined;
  const title = item
    ? 'title' in item
      ? localized(item.title, locale)
      : localized(item.org, locale)
    : '';

  const sections = isProject
    ? [
        { id: 'overview', label: copy.detail.overview },
        { id: 'highlights', label: copy.detail.highlights },
        { id: 'stack', label: copy.detail.stack },
      ]
    : [
        { id: 'overview', label: copy.detail.overview },
        { id: 'metrics', label: copy.detail.metrics },
      ];

  const linkFor = (value: string) =>
    `/${locale}/${isProject ? 'projects' : 'experience'}/${value}`;

  if (loading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center pt-24 text-sm text-gray-500">
        {copy.common.loading}
      </div>
    );
  }

  if (!item) {
    return (
      <div className="flex min-h-[60vh] flex-col items-center justify-center gap-4 pt-24 text-center">
        <h1 className="text-5xl font-normal text-[#E1E0CC]">404</h1>
        <p className="text-gray-500">{copy.common.notFound}</p>
        <button
          type="button"
          className="rounded-full border border-primary/20 px-5 py-3 text-sm text-primary hover:bg-white/5"
          onClick={() => navigate(`/${locale}`)}
        >
          {copy.detail.back}
        </button>
      </div>
    );
  }

  return (
    <div className="mx-auto grid max-w-6xl gap-8 px-6 py-24 md:grid-cols-[200px_minmax(0,1fr)] md:py-28">
      <aside className="h-max rounded-2xl bg-[#101010] p-5 md:sticky md:top-24">
        <button
          type="button"
          className="mb-4 block text-sm text-primary hover:text-[#E1E0CC]"
          onClick={() => navigate(`/${locale}`)}
        >
          ← {copy.detail.back}
        </button>
        <div className="flex flex-wrap gap-3 md:flex-col">
          {sections.map((section) => (
            <a key={section.id} href={`#${section.id}`} className="text-sm text-gray-400 hover:text-primary">
              {section.label}
            </a>
          ))}
        </div>
      </aside>

      <article className="min-w-0 space-y-4">
        <motion.header
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="rounded-3xl bg-[#101010] p-8 md:p-12"
        >
          <div className="flex flex-wrap items-center gap-3 text-xs text-gray-500">
            <span className="rounded-full border border-primary/15 px-2 py-0.5 text-primary/70">
              {isProject ? (item as Project).kind : 'experience'}
            </span>
            <span>
              {item.startedAt} — {item.endedAt || copy.common.present}
            </span>
          </div>
          <h1 className="mt-8 text-4xl font-normal tracking-tight text-[#E1E0CC] md:text-6xl">{title}</h1>
          <p className="mt-4 max-w-2xl text-lg text-primary/70 md:text-2xl">
            {isProject
              ? localized((item as Project).tagline, locale)
              : localized((item as Experience).role, locale)}
          </p>
        </motion.header>

        <section id="overview" className="rounded-3xl bg-[#212121] p-8 md:p-10">
          <SectionEyebrow label="01" tag={copy.detail.overview} />
          <h2 className="mt-4 text-2xl font-normal text-[#E1E0CC]">{copy.detail.overview}</h2>
          <p className="mt-4 max-w-3xl text-base leading-relaxed text-gray-400 md:text-lg">
            {localized(item.summary, locale)}
          </p>
        </section>

        {isProject ? (
          <>
            <section id="highlights" className="rounded-3xl bg-[#212121] p-8 md:p-10">
              <SectionEyebrow label="02" tag={copy.detail.highlights} />
              <h2 className="mt-4 text-2xl font-normal text-[#E1E0CC]">{copy.detail.highlights}</h2>
              <ul className="mt-4 space-y-3">
                {(item as Project).highlights.map((highlight) => (
                  <li key={localized(highlight, locale)} className="text-gray-400">
                    {localized(highlight, locale)}
                  </li>
                ))}
              </ul>
            </section>
            <section id="stack" className="rounded-3xl bg-[#212121] p-8 md:p-10">
              <SectionEyebrow label="03" tag={copy.detail.stack} />
              <h2 className="mt-4 text-2xl font-normal text-[#E1E0CC]">{copy.detail.stack}</h2>
              <div className="mt-4 flex flex-wrap gap-2">
                {(item as Project).tags.map((tag) => (
                  <span
                    key={tag}
                    className="rounded-full border border-primary/10 bg-black/30 px-3 py-1.5 text-sm text-gray-400"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </section>
          </>
        ) : (
          <section id="metrics" className="rounded-3xl bg-[#212121] p-8 md:p-10">
            <SectionEyebrow label="02" tag={copy.detail.metrics} />
            <h2 className="mt-4 text-2xl font-normal text-[#E1E0CC]">{copy.detail.metrics}</h2>
            <div className="mt-4 grid gap-3">
              {(item as Experience).metrics.map((metric) => (
                <div
                  key={localized(metric, locale)}
                  className="rounded-2xl border border-primary/10 bg-black/30 px-4 py-4 text-base text-primary/80"
                >
                  {localized(metric, locale)}
                </div>
              ))}
            </div>
          </section>
        )}

        <nav className="grid gap-4 md:grid-cols-2">
          {previous ? (
            <button
              type="button"
              onClick={() => navigate(linkFor(previous.slug))}
              className="rounded-2xl bg-[#212121] p-5 text-left"
            >
              <small className="text-primary">← {copy.detail.previous}</small>
              <strong className="mt-2 block font-normal text-[#E1E0CC]">
                {'title' in previous
                  ? localized(previous.title, locale)
                  : localized(previous.org, locale)}
              </strong>
            </button>
          ) : (
            <span />
          )}
          {next ? (
            <button
              type="button"
              onClick={() => navigate(linkFor(next.slug))}
              className="rounded-2xl bg-[#212121] p-5 text-right"
            >
              <small className="text-primary">{copy.detail.next} →</small>
              <strong className="mt-2 block font-normal text-[#E1E0CC]">
                {'title' in next ? localized(next.title, locale) : localized(next.org, locale)}
              </strong>
            </button>
          ) : null}
        </nav>
      </article>
    </div>
  );
}

// web/src/views/DetailView.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { useContentStore } from '@/stores/content';
import type { Experience, Locale, Localized, Project } from '@/types';

const props = defineProps<{ kind: 'project' | 'experience' }>();
const route = useRoute();
const store = useContentStore();
const item = ref<Project | Experience>();
const loading = ref(true);
const locale = computed<Locale>(() => route.params.locale === 'en' ? 'en' : 'zh');
const text = (value: Localized | undefined) => value?.[locale.value] ?? value?.zh ?? '';
const isProject = computed((): boolean => props.kind === 'project');
const items = computed(() => isProject.value ? store.data?.projects ?? [] : store.data?.experiences ?? []);
const index = computed(() => items.value.findIndex((entry) => entry.slug === route.params.slug));
const previous = computed(() => items.value[index.value - 1]);
const next = computed(() => items.value[index.value + 1]);
const title = computed(() => item.value && ('title' in item.value ? text(item.value.title) : text(item.value.org)));
const sections = computed(() => isProject.value
  ? [{ id: 'overview', label: 'detail.overview' }, { id: 'highlights', label: 'detail.highlights' }, { id: 'stack', label: 'detail.stack' }]
  : [{ id: 'overview', label: 'detail.overview' }, { id: 'metrics', label: 'detail.metrics' }]);

async function load() {
  loading.value = true;
  const slug = String(route.params.slug);
  item.value = isProject.value ? await store.project(slug) : await store.experience(slug);
  loading.value = false;
  if (title.value) document.title = `${title.value} · gutsyang`;
}

const linkFor = (slug: string) => `/${locale.value}/${isProject.value ? 'projects' : 'experience'}/${slug}`;
onMounted(load);
watch(() => [route.params.slug, route.params.locale], load);
</script>

<template>
  <div v-if="loading" class="loading-state"><t-loading size="large" /> {{ $t('common.loading') }}</div>
  <div v-else-if="!item" class="loading-state"><h1>404</h1><p>{{ $t('common.notFound') }}</p><RouterLink :to="`/${locale}`">{{ $t('detail.back') }}</RouterLink></div>
  <div v-else class="page detail-page">
    <aside class="toc bento-card">
      <RouterLink :to="`/${locale}`">← {{ $t('detail.back') }}</RouterLink>
      <a v-for="section in sections" :key="section.id" :href="`#${section.id}`">{{ $t(section.label) }}</a>
    </aside>
    <article class="detail-content">
      <header class="detail-hero bento-card">
        <span class="pill">{{ isProject ? (item as Project).kind : 'experience' }}</span>
        <span class="date">{{ item.startedAt }} — {{ item.endedAt || $t('common.present') }}</span>
        <h1>{{ title }}</h1>
        <p class="hero-slogan">{{ isProject ? text((item as Project).tagline) : text((item as Experience).role) }}</p>
      </header>
      <section id="overview" class="detail-section bento-card">
        <div class="section-number">01</div><h2>{{ $t('detail.overview') }}</h2><p>{{ text(item.summary) }}</p>
      </section>
      <section v-if="isProject" id="highlights" class="detail-section bento-card">
        <div class="section-number">02</div><h2>{{ $t('detail.highlights') }}</h2>
        <ul><li v-for="highlight in (item as Project).highlights" :key="text(highlight)">{{ text(highlight) }}</li></ul>
      </section>
      <section v-if="isProject" id="stack" class="detail-section bento-card">
        <div class="section-number">03</div><h2>{{ $t('detail.stack') }}</h2>
        <div class="tags"><t-tag v-for="tag in (item as Project).tags" :key="tag" size="large">{{ tag }}</t-tag></div>
      </section>
      <section v-else id="metrics" class="detail-section bento-card">
        <div class="section-number">02</div><h2>{{ $t('detail.metrics') }}</h2>
        <div class="metric large" v-for="metric in (item as Experience).metrics" :key="text(metric)">{{ text(metric) }}</div>
      </section>
      <nav class="detail-pagination">
        <RouterLink v-if="previous" :to="linkFor(previous.slug)" class="bento-card"><small>← {{ $t('detail.previous') }}</small><strong>{{ 'title' in previous ? text(previous.title) : text(previous.org) }}</strong></RouterLink>
        <span v-else />
        <RouterLink v-if="next" :to="linkFor(next.slug)" class="bento-card next"><small>{{ $t('detail.next') }} →</small><strong>{{ 'title' in next ? text(next.title) : text(next.org) }}</strong></RouterLink>
      </nav>
    </article>
  </div>
</template>
